# Generated by Django 3.2 on 2021-12-17 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'пользователь vk', 'verbose_name_plural': 'пользователи vk'},
        ),
    ]
